<a href="https://colab.research.google.com/github/hasindu-ramanayake/pytorch/blob/main/python_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [2]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

7

In [3]:
vector = torch.tensor([1,7])
vector
vector[1]

tensor(7)

In [4]:
MATRIX = torch.tensor([ [1,2],
                        [3,4] ])
MATRIX[1]

tensor([3, 4])

In [5]:
TENSOR = torch.tensor( [  [   [1,2,3],
                              [4,5,6],
                              [7,8,9] ] ,
                          [   [11,22,33],
                              [44,55,66],
                              [77,88,99] ]
                        ] )

TENSOR.shape

torch.Size([2, 3, 3])

In [6]:
R_TENSOR = torch.rand(5,4)
R_TENSOR

tensor([[0.9216, 0.0050, 0.5635, 0.1760],
        [0.5666, 0.0682, 0.7024, 0.9542],
        [0.4465, 0.7814, 0.4785, 0.7443],
        [0.9817, 0.3038, 0.1248, 0.4731],
        [0.8074, 0.5756, 0.3850, 0.3404]])

In [7]:
Z_TENSOR = torch.zeros(size = (3,4))
Z_TENSOR

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ONES_TENSOR = torch.ones(size=(3,4) )
ONES_TENSOR

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
range_torch = torch.arange(start=1,end=100, step=11)
range_torch

tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [10]:
like_range = torch.zeros_like(range_torch)
like_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
float_32_tensor = torch.tensor( [3.0,4.0,5.0], dtype=None, device=None, requires_grad=False )
float_32_tensor.dtype

torch.float32

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16 )
float_16_tensor.dtype

torch.float16

In [13]:
some_tensor = torch.rand(size=(3,3))
some_tensor
print(some_tensor.dtype)
print(some_tensor.device)
print(some_tensor.shape)

torch.float32
cpu
torch.Size([3, 3])


In [14]:
like_range+10, like_range*10, like_range-10, like_range/10

(tensor([10, 10, 10, 10, 10, 10, 10, 10, 10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([-10, -10, -10, -10, -10, -10, -10, -10, -10]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [15]:
%%time
torch.matmul(like_range+10,like_range-10)

CPU times: user 0 ns, sys: 1.09 ms, total: 1.09 ms
Wall time: 1.14 ms


tensor(-900)

In [16]:
### how to fix shape errors
tensor_A = torch.rand(size=(3,2))
tensor_B = torch.rand(size=(3,2))

### add transpose with .T
torch.mm(tensor_A, tensor_B.T)

tensor([[0.5175, 0.7923, 0.3594],
        [0.3115, 0.6950, 0.3285],
        [0.4589, 0.6478, 0.2905]])

In [17]:
torch.min(like_range), torch.min(like_range), torch.mean(like_range.type(torch.float32))

(tensor(0), tensor(0), tensor(0.))

In [18]:
like_range.sum(), like_range.argmin(), like_range.argmax(), like_range.sort()

(tensor(0),
 tensor(0),
 tensor(0),
 torch.return_types.sort(
 values=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])))

In [19]:
### reshaping, stacking, squeezing and unsqueezing, tensors
A_reshape = tensor_A.reshape(2,3)
A_reshape, tensor_A.reshape(6,1), tensor_A.reshape(1,6)

## tensor_A.view(6,1) share the same memory as the original ones

(tensor([[0.6995, 0.8303, 0.7618],
         [0.0805, 0.5346, 0.8419]]),
 tensor([[0.6995],
         [0.8303],
         [0.7618],
         [0.0805],
         [0.5346],
         [0.8419]]),
 tensor([[0.6995, 0.8303, 0.7618, 0.0805, 0.5346, 0.8419]]))

In [20]:
##remove all unwanted dimentions
tensor_A.reshape(6,1).squeeze(), tensor_A.reshape(6,1).squeeze().shape

(tensor([0.6995, 0.8303, 0.7618, 0.0805, 0.5346, 0.8419]), torch.Size([6]))

In [21]:
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
x.shape

torch.Size([1, 3, 3])

In [22]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [23]:
x[:,1], x[:,2], x[:,0]

(tensor([[4, 5, 6]]), tensor([[7, 8, 9]]), tensor([[1, 2, 3]]))

In [24]:
x[:,:,0], x[:,:,1], x[:,:,2]

(tensor([[1, 4, 7]]), tensor([[2, 5, 8]]), tensor([[3, 6, 9]]))

In [25]:
x[:,2,2], x[:,:,2]

(tensor([9]), tensor([[3, 6, 9]]))

In [26]:
### how to convert NumPy to Pytorch
import numpy as np
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [27]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [28]:
tensor = tensor + 10
array_tensor = tensor.numpy()
tensor, array_tensor

(tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.], dtype=torch.float64),
 array([11., 12., 13., 14., 15., 16., 17., 18., 19.]))

In [31]:
#running tensors and pytorch objects on the GPUs
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.device_count()

1